### ISSUE TITLE
Need some help about TWAIN scanner device

### ISSUE THREAD

**Issue by kittidaj** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.DS#1]
Hi Saraff
I use you example program 1 and after I pressed the scan button. The scanner scan completed  but the application still show "Calibrating..." and LED on scanner blinking (Microtek ScanMaker 9800XL plus). Do you have some ideas to close this dialog box? Or I think the problem from .dll not support for calibration setting of the scanner.
Thank you very much.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, kittidaj.
Your issue has related to the [Saraff.Twain.NET](https://github.com/saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET) project. Please, write your issue to a Issues of a [Saraff.Twain.NET](https://github.com/saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET/issues).
