### ISSUE TITLE
Count not make SampleDataSource working

### ISSUE THREAD

**Issue by irium** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.DS#2]
Could not find Entry 1 in DS: C:\WINDOWS\twain_32\SampleDataSource\Saraff.Twain.DS_x86.ds

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @irium.
Try use the Dependency Walker. See follow:
![dsx86](https://cloud.githubusercontent.com/assets/21045809/26377351/988f25f8-4018-11e7-8794-c5d7e3269dcd.jpg)

**Comment by irium** [comment]
Thank you for response.

But how can it be in .NET assembly? Looking into C# sources - there's no way to export C/C++ method from .NET Assembly dll.

Here's what Dependency Walker shows me for compiled from sources dll:

![image](https://cloud.githubusercontent.com/assets/23728/26404506/f077b5fa-409a-11e7-9ceb-fa5ec8daf3bf.png)

I'm very interesting in finding way to create twain sources on C#, but isn't successful yet.

BTW, we could continue in russian ;)

**Comment by irium** [comment]
Ahh, I see!!!

The problem is that sources for `Saraff.Twain.DS_x86/x64` distributed only in zip file from `Releases` page.
But it missing in the repository code itself. I didn't download release files, because thought that they are just compiled repository sources, as usual.

I recommend to include them into repository code.

BTW, just will try to test it works.

**Comment by irium** [comment]
Finally got it working! )) You should definitely put `Saraff.Twain.DS_x86/x64.ds` sources from `Releases` somewhere (here or in separate repo).

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Ок. Я постараюсь учесть Ваше замечание.

**Comment by irium** [comment]
Спасибо. Мне понадобилось 3 дня, чтобы догадаться попробовать посмотреть, что же там в Ваших бинарниках :) Я ожидал, что вся инфа в самом репозитории.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Есть еще и пример использования https://github.com/saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.DS/wiki/content/Saraff.Twain.DS.Screen.zip (является сертифицированным TWAIN драйвером https://resource.twain.org/twain-certified-drivers/entry/1536/)

**Comment by irium** [comment]
Спасибо.
