### ISSUE TITLE
During Installer, got an error.

### ISSUE THREAD

**Issue by pegasussanjay** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.DS#4]
I am creating a TWAIN DataSource. I have created a Installer project where I have added Merge Modules and Project Primary Output as shown here https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwainds/wiki/w5200.html. After building the Setup project, I got below error during installation.
![image](https://user-images.githubusercontent.com/30402629/35903009-63158306-0c03-11e8-8a5f-0ae46d52522d.png)

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @pegasussanjay 
Your DS assembly must declare DataSourceAttribute attribyte.

**Comment by pegasussanjay** [comment]
Yes. You are correct. I have added DataSource attribute to the Assembly and the problem get solved. Thanks! Now, I am facing some other problem. After installation the calling application get crashed during listing the TWAIN datasource. I am not sure why it is happening. I checked, .ds file and other supporting files are getting installed on C:\windows\twain_32\{GUID}\. What would be the reason for crashing? Is there anyway to log errors.

There is doubt in installer class which install the .ds file during installation. I can see, there is code written AfterInstall event that the .dll file getting renamed as .ds file. Is it correct. The .dll file is compiled of C++ project which creates a DS_Entry.

**Comment by pegasussanjay** [comment]
I just checked. After crashing the calling application, I debug the program, I am getting the null reference error in DS_Entry. See below image...
![image](https://user-images.githubusercontent.com/30402629/35918873-453b6054-0c39-11e8-8fdc-150e1f0b8511.png)

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Can you show a StackTrace of Exception?

**Comment by pegasussanjay** [comment]
Enabled Debug Mode to Mixed and got the error as below
![image](https://user-images.githubusercontent.com/30402629/35956538-7d0c6af4-0cbc-11e8-85b2-45155b724809.png)
**StackTrace:** 
   at Saraff.Twain.DS.DataSourceServices._SetConditionCode(TwIdentity appId, TwCC cc)
   at Saraff.Twain.DS.DataSourceServices.ProcessRequest(TwIdentity appId, TwDG dg, TwDAT dat, TwMSG msg, IntPtr data)
   at DS_Entry(TW_IDENTITY* pOrigin, UInt32 DG, UInt16 DAT, UInt16 MSG, Void* pData)

**Comment by pegasussanjay** [comment]
Just checked, appId is null. Below line returning _srcId as nullptr.
TwIdentity^ _srcId=(TwIdentity^)Marshal::PtrToStructure(IntPtr(pOrigin),TwIdentity::typeid);
My calling application is IfranView. I am trying to select TWAIN data source and the error coming.

![image](https://user-images.githubusercontent.com/30402629/35958592-99f03488-0cc7-11e8-9a1c-97a38153a3bf.png)

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Can you set a breakpoint in the DataSourceServices._ToLog(Exception ex) method show a Exception (include inner Exception if it exist)?

**Comment by pegasussanjay** [comment]
Inner Exception I got

The given key was not present in the dictionary.    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Saraff.Twain.DS.DataSourceServices.get_HandlerType()
   at Saraff.Twain.DS.DataSourceServices._GetDSIdentity()
   at Saraff.Twain.DS.DataSourceServices._IdentityControlProcessRequest(TwIdentity appId, TwMSG msg, IntPtr data)
   at Saraff.Twain.DS.DataSourceServices.ProcessRequest(TwIdentity appId, TwDG dg, TwDAT dat, TwMSG msg, IntPtr data)

I think, I was not able to give datasource attribute properly to the assembly of my application. Actually my application is WPF and when I compiled it as a class library, and try to build and install, the installer gives error "The assembly file containing the data source was not found", because the App dll is made in bin but not copied into File System of Installer project. See below.

![image](https://user-images.githubusercontent.com/30402629/35961069-4fe4bcf0-0cd2-11e8-9531-4995a23955ad.png)

May be I need two projects. One would be a class library and second would be my WPF Application. Class Library project would be used as twain datasource and it would internally invoke my app exe with argument that the exe is opened in TWAIN mode. 

I want your suggestion.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
1. Check result of follow line in the `private Type HandlerType` property (in DataSourceServices): `var _location = this._GetLocation();`
2. Check your DS assembly (with DataSourceAttribute) in `_location` directory.

**Comment by pegasussanjay** [comment]
Thanks for your support! You are right. The issue was related to DataSource Attribute and it is fixed now. I am closing this thread.
