### ISSUE TITLE
What is the way to transfer multiple images?

### ISSUE THREAD

**Issue by pegasussanjay** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.DS#5]
I have successfully able to transfer single bitmap image to calling application using 'BitmapDataSource' datasource. Suppose I want to transfer list of Bitmap images then what should I do? Is any other datasource available? Can you please provide any reference project for the same.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @pegasussanjay 
You can use the DataSource.XferEnvironment.PendingXfers property for transfer multiple images.
See the [OnEndXfer](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwainds/wiki/w4710.html). Also, you can see the
[Saraff.Twain.DS.Screen](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwainds/download/Saraff.Twain.DS.Screen.zip) sample. If DS show UI, you can select count of images that will be transfer to a application.

**Comment by pegasussanjay** [comment]
Is there any way to check in OnEnableDS method (see below) that the TWAIN session is opened in multiple transfer MODE

![image](https://user-images.githubusercontent.com/30402629/36021025-8f1d5692-0daa-11e8-9aee-a73f7dec3bcf.png)

 this.XferEnvironment.PendingXfers always returns 0 (in single transfer mode and multi transfer mode)

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
You can check value of the XferCount capability. 
```C#
    /// <summary>
    /// Invoked to indicate that the Source has data that is ready to be transferred.
    /// </summary>
    protected override void OnXferReady() {
        if(this.XferEnvironment.PendingXfers==0) {
            this.XferEnvironment.PendingXfers=(ushort)Math.Abs((short)this[TwCap.XferCount].Value);
        }
        this._Acquire();

        base.OnXferReady();
    }
```
Or you can can create your own (custom) capability.
See [Adding new capabilities](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwainds/wiki/w1420.html)

**Comment by pegasussanjay** [comment]
`(short)this[TwCap.XferCount].Value ` returns -1 in both case (single mode and multiple mode)

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
It's possible, because -1 is default value (**CAP_XFERCOUNT Description**: The application is willing to accept this number of images. **Application**: Application is willing to transfer multiple images. **Source**: If the application limits the number of images it is willing to receive, the Source should not make
more transfers available than the specified number.)

Therefore, application must define count of images to transfer. Or, if XferCount=-1, DS can transfer multiple images and send TWRC_CANCEL when all images transfered.

**Comment by pegasussanjay** [comment]
Got it Thanks! 

There is one question regarding 'Close'. Some applications specify that 'Close TWAIN dialog after acquiring the image' (IrfanView). So is any 'flag' available that we can receive in OnEnableDS that the calling application is willing to close after transfer?

![image](https://user-images.githubusercontent.com/30402629/36027406-2eec0c02-0dc1-11e8-9c24-22b9109d377b.png)

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
No, because "Close TWAIN dialog" mean that a application will be send DG_CONTROL / DAT_IDENTITY / MSG_CLOSEDS (invoke [OnDisableDS](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwainds/wiki/w4430.html)) after all images has been transferred.

**Comment by pegasussanjay** [comment]
Ok. Thanks!
