### ISSUE TITLE
Borland

### ISSUE THREAD

**Issue by jshafer817** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.DS#6]
Great work dude! I have tested the screen sample with many programs so far so good, except for 1 that is written in Borland. I did some googling and ran across this:
http://www.eztwain.com/borland-issue.htm

Not sure how to test this, I did find a Borland scanner app, and your twain driver worked.. But perhaps the Borland app was compiled to ignore floating point exceptions... I don't know much about Borland.. or Floating Point. Thought I would post this to see what you think.

What happens is.. sending the image causes an error in a dental program called XDR... I don't have the source code so I am not sure what is happening.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @jshafer817 
About the floating point exceptions, the Saraff.Twain.DS don't throws any exceptions to a DSM or a application. So the Saraff.Twain.DS must work with any apps.

You wrote: "What happens is.. sending the image causes an error in a dental program called XDR..."
Can you provide more information?

**Comment by jshafer817** [comment]
I did more testing, and as it turns out the software I was testing cannot handle high resolution images or something. No issue! Their software... has issues.
