### ISSUE TITLE
Issue with ScreenDS Sample

### ISSUE THREAD

**Issue by jshafer817** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.DS#7]
Some programs are slow at handling the acquire, but I found that the best fix is, adding a progress bar dialog form that does stuff while the acquire is happening. Fixed a ton of stuff I had.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @jshafer817 
The Saraff Screen DS sample is intended to demonstrate the TWAIN DS development capabilities.
If you need, then you can make changes to the sample on the terms of the GNU GPLv3 license.
