### ISSUE TITLE
Support of ExtImageInfo for Barcode Text in DAT_EXTIMAGEINFO

### ISSUE THREAD

**Issue by taylorjimbo** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.DS#8]
Does the Saraff.TwainDS support the ExtImageInfo? 

I have Barcode Text that I need to pass to the application. 
According to the TWAIN spec this needs to be in DAT_EXTIMAGEINFO.

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @taylorjimbo 
You can implement it. Override the [OnProcessRequest](https://saraff-9eb1047a4beb4cef8506b29ba325bd5a.github.io/sarafftwainds/wiki/w4110.html) method.
